const URL_LIST = [
  'https://www.oschina.net/',
  "https://www.baidu.com/s?ie=UTF-8&wd=hello",
  "https://cn.bing.com/search?q=hello",
  "https://www.bilibili.com/",
  "https://www.csdn.net/",
  "https://www.google.com/search?q=hello",
  "https://github.com/",
  "https://pwa.clicli.me/",
  "https://www.youtube.com/",
  "https://segmentfault.com/",
  "https://www.cnblogs.com/",
  "https://juejin.im/",
  "https://www.jianshu.com/",
  "https://stackoverflow.com/",
  "https://www.baidu.com",
  "https://www.google.com",
  "https://cn.bing.com",
  "https://www.douban.com/",
  "https://en.wikipedia.org/wiki/Main_Page",
  "https://www.facebook.com/",
  "https://twitter.com/",
  "https://www.amazon.com/",
  "https://play.google.com/store",
  "https://www.netflix.com/jp-en/",
  "https://www.yahoo.com/",
  "http://daily.zhihu.com/",
  "https://www.sina.com.cn/",
  "https://www.toutiao.com/",
  "https://pornhub.com/",
  "https://my.oschina.net/ahaoboy",
  "https://www.reddit.com/",
  "https://yahoo.com/",
  "https://juejin.cn/",
  "https://www.toutiao.com/"
]

module.exports = URL_LIST
