name: CI

on: [push]
# on:
#   schedule:
    # * is a special character in YAML so you have to quote this string
#     - cron:  '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create local changes
        run: |
          npm i
          npm   start
      - name: Commit files
        run: |
          git config --local user.email "504595380@qq.com"
          git config --local user.name "ahaoboy"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
